services:
  - type: web
    name: finscale-app
    env: node
    plan: free
    buildCommand: npm install && npm run build:full
    startCommand: npm start
    envVars:
      - key: SERVER_PORT
        value: 10000
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: TELEGRAM_BOT_API
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: NGROK_AUTHTOKEN
        sync: false
